### ISSUE TITLE
Foreman API v1 support

### ISSUE THREAD

**Issue by rolze** [davidblaisonneau-orange/foreman#5]
Hello,

how easy/difficult would it be to support the old Foreman API v1 too?

It's feasible at all? 
If yes, I'll do a fork and give it a try....

Cheers
Roland

**Comment by davidblaisonneau-orange** [comment]
Hello,

Hard to say, it will depend on the degree of details you need, v1 is less detailed than v2, but the structure seems to be close. In a first step you can try commenting all unexisting ressources in v1 and focus on one item for the debug.

BR

**Comment by rolze** [comment]
Thx for your response. I found another lib: https://github.com/david-caro/python-foreman
This one is more low-level, but responds to different API versions.

Cheers
Roland
